src/Socket/Server.php
In PHP socket programming, the `SO_LINGER` option is used to control the behavior of a socket when it is closed. The linger option specifies whether the socket should remain active for a period of time after it is closed, allowing any pending data to be sent or received.
- `l_linger` specifies the amount of time, in seconds, to linger after the socket is closed. In this case, it is set to `0`, meaning the socket will not linger and will be closed immediately.
- `l_onoff` is a boolean value that determines whether the `l_linger` option is enabled (`1`) or disabled (`0`). In this case, it is set to `1`, indicating that the `l_linger` option is turned on.
=> Adds socket option that fixes the problem with long wait of closing TCP port after closing socket

README.md, bin/trap.bat, composer.json, src/Client/TrapHandle.php, src/Client/TrapHandle/ContextProvider/Source.php, src/Client/TrapHandle/Counter.php, src/Client/TrapHandle/Dumper.php, src/Client/TrapHandle/StackTrace.php, src/functions.php
```php
// Limit the depth of the dumped structure
trap($veryDeepArray)->depth(3);
foreach ($veryLargeArray as $item) {
// We don't need to dump more than 3 items
trap($item)->times(3);
}
// Dump only if the condition is true
trap($animal)->once()->if($var instanceof Animal\Cat);
```
=> Trap options: `if()`, `once()`, `times()`, `depth()`

src/Sender/Frontend/RPC.php, src/Sender/Frontend/Service.php
Now additional arguments are passed via Websocket RPC.
`Delete all events` action consider passed event ID list to delete
Part of #36
=> Considers id list in `Delete events` action

src/Application.php, src/Cancellable.php, src/Client/TrapHandle/Dumper.php, src/Command/Run.php, src/Destroyable.php, src/Logger.php, src/Sender/Console/Renderer/Sentry/Exceptions.php, src/Sender/Console/Renderer/VarDumper.php, src/Socket/Client.php, src/Socket/Exception/ClientDisconnected.php, src/Socket/Exception/ServerStopped.php, src/Socket/Server.php
Added a constant delay of 100ms before an instant disconnect.
Run command now consumes signals
Added Cancellable and Destroyable interfaces
In some cases, the connection to the client closes too quickly. The client doesn't have time to receive all the content.
This problem could have been solved by removing this fragment:
https://github.com/buggregator/trap/blob/929ce1f3d520e66a1e567f9def83020c6f099845/src/Socket/Server.php#L40-L41
but the convenience of restarting the server is still important.
=> Fix fast connection closing

composer.json, src/Command/Run.php
Added compatibility with Symfony Console 7.0. There was an error before these changes:
```
PHP Fatal error:  Declaration of Buggregator\Trap\Command\Run::handleSignal(int $signal): int|false must be compatible with Symfony\Component\Console\Command\SignalableCommandInterface::handleSignal(int $signal, int|false $previousExitCode = 0): int|false in ... src/Command/Run.php on line 110
```
Removed support for symfony/console 5.x and 6.0 because the method in the interface has a void return type:
https://github.com/symfony/console/blob/v5.4.34/Command/SignalableCommandInterface.php#L29
https://github.com/symfony/console/blob/v6.0.19/Command/SignalableCommandInterface.php#L29
=> Add compatibility with Symfony Console 7.0

LICENSE.md, src/Client/TrapHandle.php, src/Client/TrapHandle/Counter.php, src/Sender/Frontend/Http/StaticFiles.php, tests/Unit/Client/Base.php, tests/Unit/Client/FunctionTrapTest.php, tests/Unit/Client/TrapTest.php
More tests
UI StaticFiles middleware caches UI files content
Now `trap()` doesn't print stack trace. Added `trap()->stackTrace()` instead.
=> Add `trap()->stackTrace()`; maintenance

README.md, src/Client/TrapHandle.php, src/Info.php, tests/Unit/Client/TrapTest.php
Add method `trap()->return()`
```php
/**
* Send the dump if possible and then return the dumped value immediately.
*
* @param int|string $key Position in the value sequence (0-based) or name of the named argument.
*
* ```php
* trap(42)->return(); // 42
* trap(count: 42, value: 90)->return('value'); // 90
* trap(foo: 'bar')->return(0); // 'bar'
* trap()->return(); // exception
* ```
*/
public function return(int|string $key = 0): mixed
```
Sometimes you have to dump the argument value, which is calculated and not stored in a variable. In such cases, you have to extract the code into a separate variable, which is not very convenient. It's easier to wrap the value with `trap(  <value>  )->return()`.
=> Add method `trap()->return()`

README.md, src/Command/Run.php
The `--port` (`-p`) parameter is a plural value
Although Trap is capable of identifying the type of traffic, launching to listen on multiple ports can be convenient to avoid making changes to configuration files.
=> Added the ability to run the program listening on multiple ports

psalm-baseline.xml, psalm.xml, src/Proto/Frame/Smtp.php, src/Sender/Console/Renderer/SentryEnvelope.php, src/Sender/Console/Renderer/Smtp.php, src/Sender/Console/Renderer/TemplateRenderer.php, src/Sender/Console/Renderer/VarDumper.php, src/Sender/Console/Support/Common.php, src/Sender/Console/Support/Files.php, src/Sender/Console/Support/Tables.php, src/Sender/ConsoleSender.php, src/Socket/Client.php, src/Socket/Server.php, src/Support/StreamHelper.php, src/Traffic/Dispatcher/Http.php, src/Traffic/Dispatcher/Smtp.php, src/Traffic/Message/Headers.php, src/Traffic/Message/Multipart/Field.php, src/Traffic/Message/Multipart/File.php, src/Traffic/Message/Multipart/Part.php, src/Traffic/Message/Smtp.php, src/Traffic/Parser/Http.php, src/Traffic/Parser/Smtp.php, src/functions.php, tests/Unit/Traffic/Parser/HttpParserTest.php
First part of clear psalm-baseline.yml. I decided split this request for few parts for more ease review)
=> Fix psalm, clear psalm-baseline.yaml

src/Command/Run.php, src/Info.php, src/Sender/Frontend/Message/Connect.php, src/Sender/Frontend/Message/Settings.php, src/Sender/Frontend/Message/Version.php, src/Sender/RemoteSender.php
Trap uses version, that is being read from file, instead of using const.
To implement auto-release management, without manual interaction.
=> feat: use latest version from auto-incrementing file

.gitignore, .phive/.gitignore, .phive/phars.xml
Because of root .gitignore `/.*/` rule, there were missing files in .phive folder, which raised error, when using such commands:
```bash
make lint-composer
make phive
make lint-deps
```
=> ci: add missing phive repository files

composer-require-checker.json, composer.json, composer.lock
Added missing `composer-require-checker.json` file
This tool helps to check for external dependencies, that are not listed as required in `composer.json` file.
=> ci: add composer-require-checker file to support local dep linting

src/Client/TrapHandle.php, tests/Unit/Client/TrapTest.php
Nothing changes, just sugar
Before 
```php
trap()->context(language: 'php')
```
After
```php
trap()->code('php')
```
The presence of a method will give you an immediate understanding of the presence of this feature even without referring to the documentation, it will be easier to remember, and it will be immediately clear what’s what
- Tested
=> Add `trap()->code()` sugar

.github/.release-please-config.json
Do not include v prefix in release versions
Example:
v1.8.0 -> 1.8.0
=> ci: to not include version prefix

.github/workflows/static-analysis.yml, phpstan.neon.dist, tests/Unit/Client/FunctionTrapTest.php, tests/Unit/Client/TrTest.php, tests/Unit/Client/TrapTest.php, tests/Unit/Handler/Router/RouterTest.php, tests/Unit/Sender/Frontend/EventsStorageTest.php, tests/Unit/Traffic/Dispatcher/HttpTest.php, tests/Unit/Traffic/Dispatcher/VarDumperTest.php, tests/Unit/Traffic/Emitter/HttpTest.php, tests/Unit/Traffic/Message/Multipart/FieldTest.php, tests/Unit/Traffic/Message/Multipart/FileTest.php, tests/Unit/Traffic/Parser/HttpParserTest.php, tests/Unit/Traffic/Parser/MultipartBodyParserTest.php, tests/Unit/Traffic/Parser/SmtpParserTest.php, tests/Unit/Traffic/Proto/Server/Version/V1Test.php
CI: Psalm and Phpstan work in separated workflows
=> CI: separate psalm and phpstan workflows

.github/workflows/testing.yml, composer.json, pest.xml.dist, tests/Unit/Client/FunctionTrapTest.php, tests/Unit/Client/TrTest.php
Pest is used for arch tests only. It uses separated config file to not to break phpunit
pest doesn't work well but we need to have arch tests
- Closes #112
- Tested
=> CI: separate pest config and isolate pest from unit tests

README.md, psalm.xml, src/Application.php, src/Command/Run.php, src/Handler/Http/Handler/Fallback.php, src/Sender/Frontend/Http/Pipeline.php, src/Service/Container.php
- Add ability to process HTTP events and UI on the same port
- Default open ports now the same as in Buggregator Server: `1025`, `8000`, `9912` and `9913`
To use same port for UI and data collection and to be interchangeable with the Buggregator Server
- Closes #121 
- Tested
=> Add ability to process HTTP events and UI on the same port

README.md, src/Command/Run.php, src/Config/Server/TcpPorts.php
Fixed default ports option
Update documentation: added info about phar disctributive
=> Fix docs and ports option

README.md, src/Traffic/Message/Multipart/Part.php, src/Traffic/Parser/Http.php, src/Traffic/Parser/MultipartType.php, src/Traffic/Parser/Smtp.php, tests/Unit/Traffic/Parser/MultipartBodyParserTest.php
Fix parsing for `multipart/mixed` data when:
- There is trailing dot (`.`) in raw data. In this case connection was frozen.
- A multipart field doesn't contain `Content-Disposition` header. In this case parser just failed and zero chunks was parsed.
Related with https://github.com/buggregator/frontend/issues/178
=> Better HTTP/SMTP Multipart parsing

psalm-baseline.xml, src/Client/Caster/ProtobufCaster.php, src/Sender/Console/Renderer/Profiler.php, src/Sender/Console/Renderer/Sentry/Exceptions.php, src/Sender/Console/Renderer/VarDumper.php, src/Sender/Console/Support/Tables.php, src/Support/Stream/Base64DecodeFilter.php, src/Traffic/Message/Multipart/Part.php, src/Traffic/Parser/Http.php
Fixed some Psalm errors and added types
[](https://github.com/buggregator/trap/issues/32)
- Part of https://github.com/buggregator/trap/issues/32
- Tested
=> Fix Psalm issues

.github/workflows/refactoring.yml, .github/workflows/static-analysis.yml, .php-cs-fixer.dist.php, composer.json, composer.lock, rector.php, src/Client/Caster/ProtobufCaster.php, src/Client/Caster/Trace.php, src/Client/Caster/TraceFile.php, src/Client/TrapHandle.php, src/Client/TrapHandle/ContextProvider/Source.php, src/Client/TrapHandle/Dumper.php
Add Rector to CI. Now only for one directory - `src/Client`.
Because this world needs more static analysis!
=> Add Rector to CI

psalm.xml, src/Application.php, src/Sender/Console/Renderer/Sentry/Exceptions.php, src/Socket/Client.php, src/Socket/Server.php
Separate polling intervals for sockets have been added using the methods socket_select() and socket_accept().
To avoid errors on socket resource due to excessively frequent polling of the state.
- Closes #139 
- Tested
=> Separate polling intervals for sockets

src/Application.php, src/Command/Run.php, src/Config/Server/App.php, src/Config/Server/SocketServer.php, src/Config/Server/TcpPorts.php
Added envs:
`TRAP_TCP_POLLING_INTERVAL` to configure sockets polling interval
`TRAP_MAIN_LOOP_INTERVAL` to configure main loop interval
To empirically determine the best default values.
- Part of #139 
- Tested
=> Add config for main loop interval and socket polling interval

src/Sender/MailToFileSender.php, src/Test/Mock/StreamClientMock.php, src/Traffic/Dispatcher/Smtp.php, src/Traffic/Message/Smtp.php, tests/Unit/Traffic/Dispatcher/SmtpTest.php, tests/Unit/Traffic/Parser/SmtpParserTest.php
Better SMTP support. Added ability to handle multiple emails on one connection.
- Closes #152
- Tested
=> Support multiple emails in one connection

src/Sender/MailToFileSender.php, tests/Unit/Sender/MailToFileSenderTest.php
=> Allow `_` in email names in MailToFileSender

composer.json, composer.lock, src/Command/Run.php, src/Sender/SenderRegistry.php
All the senders now are created when needed
To avoid creating unnecessary directories during ***toFile senders initialization
=> Make Senders lazy

phpunit.xml.dist, src/Traffic/Parser/Smtp.php, tests/Unit/Traffic/Parser/SmtpParserTest.php
Supported multiline headers parsing
See RFC822 section 3.1.3)
- Closes #159 
- Tested
=> SMTP: improve parsing of multiline headers (

.github/workflows/apply-labels.yml, .github/workflows/build-phar-release.yml, .github/workflows/coding-standards.yml, .github/workflows/refactoring.yml, .github/workflows/security.yml, .github/workflows/static-analysis.yml, .github/workflows/testing.yml, composer.json, composer.lock, psalm-baseline.xml, src/Client/TrapHandle.php
$_ENV is used as a fallback store to get VAR_DUMPER_* values
Some magic frameworks may move needed values from $_SERVER to $_ENV
=> Use _ENV to get VAR_DUMPER envs

src/Handler/Http/Middleware/SentryTrap.php, src/Handler/Http/Middleware/SentryTrap/EnvelopeParser.php, src/Sender/Console/Renderer/Sentry/Header.php
Increased parsing JSON level.
Sentry messages nay have greater level than 4.
Fix #182
=> Fix Sentry envelope parsing

src/Client/TrapHandle.php
`TrapHandle` checks multiple sources of environment variables (`$_SERVER` array, `$_ENV` array, local-only environment via `getenv($name, true)`, and global environment via `getenv($name)`) instead of `$_SERVER` and `$_ENV` only.
Environment variable access in PHP can be inconsistent depending on configuration. The `$_ENV` superglobal may not be populated in all PHP environments, particularly when `variables_order` directive doesn't include "E" (by default).
Using `getenv()` provides more reliable access to environment variables across different PHP configurations, ensuring the Trap debugging functionality works consistently.
- Closes
- Tested
=> Use `getenv()` for getting environment variable values
